version: '3.4'

networks:
  dev:
    driver: bridge

services:
  eateasy_app:
    image: docker.io/library/eateasy
    depends_on:
      - "app_db"
    container_name: eateasy-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DbUser=${DbUser}
      - DbPassword=${DbPassword}
      - DbServer=${DbServer}
      - DbName=${DbName}
      - DbPort=5432
      - ASPNETCORE_URLS=http://+80 
    networks:
      - dev
  
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=${DbUser}
      - POSTGRES_PASSWORD=${DbPassword}
      - POSTGRES_DB=${DbName}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dev

